-- Autogenerated: do not edit this file

CREATE TABLE JOB_INSTANCE  (
    JOB_NAME              VARCHAR(100) NOT NULL  PRIMARY KEY,
    START_DATE            TIMESTAMP DEFAULT NULL ,
    END_DATE              TIMESTAMP DEFAULT NULL ,
    TOTAL_COUNT           BIGINT    DEFAULT 0,
    SUCCESS_COUNT         BIGINT  DEFAULT 0,
    SKIP_COUNT            BIGINT  DEFAULT 0,
    EXIT_CODE             VARCHAR(100) DEFAULT 'UNKOWN'
) ;

CREATE TABLE JOB_TRACE  (
    JOB_NAME              VARCHAR(100) NOT NULL,
    START_DATE            TIMESTAMP DEFAULT NULL,
    ITEM_ID               VARCHAR(100) NOT NULL,
    END_DATE              TIMESTAMP DEFAULT NULL,
    TRACE                 VARCHAR(2500),
    constraint JOB_TRACE_UN unique (JOB_NAME,START_DATE,ITEM_ID)--,
    --constraint JOB_TRACE_FK foreign key (JOB_NAME)
    --references JOB_INSTANCE(JOB_NAME)
) ;


